SistemaRestaurantes/SistemaRestaurantes/WebSite/Models/PratoView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebSite.Models
{
    public class PratoView
    {
        public int ID { get; set; }

        public string Nome { get; set; }

        public string Valor { get; set; }

        public string NomeRestaurante  { get; set; }

        public int RestauranteID { get; set; }
    }
}

SistemaRestaurantes/SistemaRestaurantes/WebSite/Controllers/PratoController.cs
using RepositorioDados.Entidades;
using RepositorioDados.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSite.Models;
using WebSite.Utils;

namespace WebSite.Controllers
{
    public class PratoController : Controller
    {
        // GET: Prato
        public ActionResult Index()
        {
            return View();
        }

        // GET: Restaurante
        public ActionResult Formulario()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetPratos()
        {
            // disponibiliza o repositorio para ser usado
            RepositorioPrato repositorio = new RepositorioPrato();
            // busca todos os pratos com seus respctivos restaurantes
            List<Prato> pratosBD = repositorio.SelectEager().ToList();
            // lista de pratos que serão enviadas via json /* uma solulção pra reference circular
            List<PratoView> pratos_view = new List<PratoView>();
            // percorre os pratos trasidos so banco e os tranformam em Prato view
            foreach (var prato in pratosBD)
            {
                pratos_view.Add(new PratoView() {
                    ID = prato.ID,
                    Nome = prato.Nome,
                    NomeRestaurante = prato.Restaurante.Nome,
                    RestauranteID = prato.RestauranteID,
                    Valor = prato.Valor.ToString()
                });
            }
            // ResponseView objeto usado para trafegar dados do back end para front end
            ResponseView response = new ResponseView() { Status = Status.OK, Result = pratos_view };
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SalvarPrato(PratoView prato)
        {
            // disponibiliza o repositorio para ser usado
            RepositorioPrato repositorio = new RepositorioPrato();
            // Devo atualizar
            if (prato.ID > 0) {
                // busca prato do banco para ser atualizado
                Prato pratoBD = repositorio.Select().Where(p => p.ID == prato.ID).FirstOrDefault();
                // Edita os atributos
                pratoBD.Nome = prato.Nome;
                pratoBD.Valor = Convert.ToDouble(prato.Valor);
                pratoBD.RestauranteID = prato.RestauranteID;
                // Salva na base o praro editado
                repositorio.Update(pratoBD);
            }
            // Devo Adicionar
            else
                repositorio.Insert(new Prato() { Nome = prato.Nome, Valor = Convert.ToDouble(prato.Valor), RestauranteID = prato.RestauranteID });

            // ResponseView objeto usado para trafegar dados do back end para front end
            ResponseView response = new ResponseView() { Status = Status.OK, Result = null };
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult RemovePrato(int idPrato)
        {
            // disponibiliza o repositorio para ser usado
            RepositorioPrato repositorio = new RepositorioPrato();
            // busca o prato no banco de dados
            Prato prato = repositorio.Select().FirstOrDefault(p => p.ID == idPrato);
            // deleta o prato do banco
            repositorio.Delete(prato);
            // ResponseView objeto usado para trafegar dados do back end para front end
            // Devolvo o Id para o front excluir a linha do prato com esse Id
            ResponseView response = new ResponseView() { Status = Status.OK, Result = idPrato };
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetPrato(int idPrato)
        {
            // disponibiliza o repositorio para ser usado
            RepositorioPrato repositorio = new RepositorioPrato();
            // busca o prato no banco de dados "Prato com seu Restaurante"
            Prato pratoDB = repositorio.GetPratoEager(idPrato);
            // tranforma em pratoBD em PratoView
            PratoView prato = new PratoView()
            {
                ID = pratoDB.ID,
                Nome = pratoDB.Nome,
                NomeRestaurante = pratoDB.Restaurante.Nome,
                RestauranteID = pratoDB.RestauranteID,
                Valor = pratoDB.Valor.ToString()
            };
            // ResponseView objeto usado para trafegar dados do back end para front end
            // envia para o front o objeto Prato View
            ResponseView response = new ResponseView() { Status = Status.OK, Result = prato };
            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }
}

SistemaRestaurantes/SistemaRestaurantes/WebSite/Views/Prato/Formulario.cshtml
@{
    ViewBag.Title = "Formulario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading"></div>
    <div class="panel-body">
        <form onsubmit="Salvar()">
            <input type="hidden" name="id_pra" id="id_pra" value="0">
            <div class="form-group">
                <label for="nome">Nome</label>
                <input type="text" class="form-control" id="nome" name="nome" required placeholder="Nome do Prato">
            </div>
            <div class="form-group">
                <label for="valor">Valor</label>
                <input type="number" class="form-control" id="valor" name="valor" step="0.01" required placeholder="Valor do Prato" min="1" max="1000">
            </div>
            <div class="form-group">
                <label for="restaurantes">Nome</label>
                <select id="restaurantes" name="valor" class="form-control" required></select>
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>
</div>
<p class="text-center">
    <a href="@Url.Action("Index", "Prato")" class="btn btn-danger">
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        Cancelar
    </a>
</p>

@section scripts {
    <script src="~/js/formprato.js"></script>
}

SistemaRestaurantes/SistemaRestaurantes/WebSite/Views/Prato/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading"><p class="text-center text-muted"><b>PRATOS</b></p></div>
    <div class="panel-body">
        <button class="btn btn-success" id="btn_toobar" onclick="AddPrato()"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Novo</button>
        <table id="tablePratos" class="table table-bordered"
               data-toggle="table"
               data-pagination="true"
               data-unique-id="ID"
               data-search="true"
               data-search-align="left"
               data-toolbar-align="right"
               data-toolbar="#btn_toobar">
            <thead>
                <tr>
                    <th data-field="ID" data-sortable="true">ID</th>
                    <th data-field="Nome" data-sortable="true">Nome</th>
                    <th data-field="Valor" data-sortable="true" data-formatter="FormataPrecos">Valor</th>
                    <th data-field="NomeRestaurante" data-sortable="true">Nome Restaurante</th>
                    <th data-field="ID" data-formatter="Acoes">Ações</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>


@section scripts {
    <script src="~/js/prato.js"></script>
}