SistemaRestaurantes/SistemaRestaurantes/WebSite/Controllers/RestauranteController.cs
using RepositorioDados.Entidades;
using RepositorioDados.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSite.Utils;

namespace WebSite.Controllers
{
    public class RestauranteController : Controller
    {
        // GET: Restaurante
        public ActionResult Index()
        {
            return View();
        }

        // GET: Restaurante
        public ActionResult Formulario()
        {
            return View();
        }
        
        [HttpGet]
        public ActionResult GetRestaurantes()
        {
            // disponibiliza o repositorio para ser usado
            RepositorioRestaurante repositorio = new RepositorioRestaurante();
            // lista de restaurante que sera devolvida
            List<Restaurante> restaurantes = new List<Restaurante>();
            // busca no banco os restaurantes
            restaurantes = repositorio.Select().OrderBy(r => r.Nome).ToList();
            // ResponseView objeto usado para trafegar dados do back end para front end
            ResponseView response = new ResponseView() { Status = Status.OK, Result = restaurantes };
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SalvarRestaurante(Restaurante restaurante)
        {
            // disponibiliza o repositorio para ser usado
            RepositorioRestaurante repositorio = new RepositorioRestaurante();
            // Devo atualizar
            if (restaurante.ID > 0) { repositorio.Update(restaurante); }
            // Devo Adicionar
            else { repositorio.Insert(restaurante); }
            // ResponseView objeto usado para trafegar dados do back end para front end
            ResponseView response = new ResponseView() { Status = Status.OK, Result = null };
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult RemoveRestaurante(int idRestaurante)
        {
            // disponibiliza o repositorio para ser usado
            RepositorioRestaurante repositorio = new RepositorioRestaurante();
            // bucas restaurante da base de dados com seus pratos
            Restaurante restaurante = repositorio.SelectEager().FirstOrDefault(r => r.ID == idRestaurante);
            // Apaga o restaurante e seus ratos
            repositorio.Delete(restaurante);
            // ResponseView objeto usado para trafegar dados do back end para front end
            // devolve o id para o front para remover a linha da tabela com esse id
            ResponseView response = new ResponseView() { Status = Status.OK, Result = idRestaurante };
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetRestaurante(int idRestaurante)
        {
            // disponibiliza o repositorio para ser usado
            RepositorioRestaurante repositorio = new RepositorioRestaurante();
            // bucas restaurante da base de dados lazy
            Restaurante restaurante = repositorio.Select().FirstOrDefault(r => r.ID == idRestaurante);
            // ResponseView objeto usado para trafegar dados do back end para front end
            // devolve o restaurante para o front
            ResponseView response = new ResponseView() { Status = Status.OK, Result = restaurante };
            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }
}

SistemaRestaurantes/SistemaRestaurantes/WebSite/Views/Restaurante/Formulario.cshtml
@{
    ViewBag.Title = "Formulario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading"></div>
    <div class="panel-body">
        <form onsubmit="Salvar()">
            <input type="hidden" name="id_res" id="id_res" value="0">
            <div class="form-group">
                <label for="nome">Nome</label>
                <input type="text" class="form-control" id="nome" name="nome" required placeholder="Nome do Restaurante">
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>
</div>
<p class="text-center">
    <a href="@Url.Action("Index", "Restaurante")" class="btn btn-danger">
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        Cancelar
    </a>
</p>

@section scripts {
    <script src="~/js/formrestaurante.js"></script>
}

SistemaRestaurantes/SistemaRestaurantes/WebSite/Views/Restaurante/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading"><p class="text-center text-muted"><b>RESTAURANTES</b></p></div>
    <div class="panel-body">
        <button class="btn btn-success" id="btn_toobar" onclick="AddRestaurante()"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Novo</button>
        <table id="tableRestaurantes" class="table table-bordered"
               data-toggle="table"
               data-pagination="true"
               data-unique-id="ID"
               data-search="true"
               data-search-align="left"
               data-toolbar-align="right"
               data-toolbar="#btn_toobar">
            <thead>
                <tr>
                    <th data-field="ID" data-sortable="true">ID</th>
                    <th data-field="Nome" data-sortable="true">Nome</th>
                    <th data-field="ID" data-formatter="Acoes">Ações</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>


@section scripts {
    <script src="~/js/restaurante.js"></script>
}